import { Montserrat } from "next/font/google";
import { ColorSchemeScript } from "@mantine/core";
import { Providers } from "@/providers";

import type { Metadata } from "next";

import "@mantine/core/styles.css";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Layout } from "@/components";

const montserrat = Montserrat({
  subsets: ["latin", "cyrillic"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk">
      <head>
        <ColorSchemeScript />
      </head>
      <body className={montserrat.className}>
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
    </html>
  );
}
